### ISSUE TITLE
Error opening terminal: unknown.

### ISSUE THREAD

**Issue by saudiqbal** [nickola/web-console#59]
I keep getting this error if I use nano or some other command.

**Comment by zombozo12** [comment]
Please give us more information.

**Comment by saudiqbal** [comment]
If I type ls I can see the listing if I type nano /file.txt I get Error opening terminal: unknown.

**Comment by zombozo12** [comment]
Afaik, this project doesn't support execute arbitrary screen-based programs on a remote machine such as nano or vim. I just tested it, and I've been using web-console since 2017 and can never run screen-based programs. Another approach to use nano is directly connected to your remote server using `ssh`.
